### PR TITLE
fix: exclude unwanted dir

### LINKED ISSUE #177: Excel extractor attempts to extract ._ files from an archive
Repro steps:

Zip 3 xlsx files into an archive on Mac

Upload to Flatfile using plugin-excel-extractor

Result:

Screenshot 2023-08-11 at 3 17 08 PM

### PR DESCRIPTION
**Pull request by carlbrugger**
This PR excludes the `__MACOSX` directory from being uploaded to Flatfile. Fixes #177.

### CODE REVIEW

File: plugins/zip-extractor/src/index.ts [hunk 1]
```diff
@@ -28,8 +28,9 @@ export const ZipExtractor = () => {
             progress: 50,
             info: 'Uploading files',
           })
-          zipEntries.forEach(async (zipEntry) => {
+          const uploadPromises = zipEntries.map(async (zipEntry) => {
             if (
+              !zipEntry.entryName.startsWith('__MACOSX') &&
```
Comment (hansjhoffman) [inline plugins/zip-extractor/src/index.ts:33]: ❔ `__MACOSX` is a directory so why doesn't `isDirectory` work?

File: plugins/zip-extractor/src/index.ts [hunk 2]
```diff
@@ -28,8 +28,9 @@ export const ZipExtractor = () => {
...
               !zipEntry.entryName.startsWith('.') &&
               !zipEntry.entryName.match('.DS_Store') &&
```
Comment (hansjhoffman) [inline plugins/zip-extractor/src/index.ts:35]: ❔ How do these 2 not overlap?

File: plugins/zip-extractor/src/index.ts [hunk 3]
```diff
@@ -28,8 +28,9 @@ export const ZipExtractor = () => {
             progress: 50,
             info: 'Uploading files',
           })
-          zipEntries.forEach(async (zipEntry) => {
+          const uploadPromises = zipEntries.map(async (zipEntry) => {
             if (
+              !zipEntry.entryName.startsWith('__MACOSX') &&
               !zipEntry.entryName.startsWith('.') &&
```
Comment (alexhollenbeck) [inline plugins/zip-extractor/src/index.ts:34]: Seems like this already should have solved the issue that I reported - the extraneous files all started with `.`. Why does the change in this PR fix the issue?

File: plugins/zip-extractor/src/index.ts (hunk 1 above)
Comment (carlbrugger) [reply plugins/zip-extractor/src/index.ts:33]: @hansjhoffman `isDirectory` matches on `__MACOS` but doesn't on `__MACOS/file.ext`. We want to traversal each directory and upload the contents. This check stops traversal of the `__MACOS` directory since we know the contents are not relevant.

File: plugins/zip-extractor/src/index.ts (hunk 3 above)
Comment (carlbrugger) [reply plugins/zip-extractor/src/index.ts:34]: @alexhollenbeck apparently `entryName` contains the entire path.

File: plugins/zip-extractor/src/index.ts (hunk 2 above)
Comment (carlbrugger) [reply plugins/zip-extractor/src/index.ts:35]: @hansjhoffman apparently `entryName` contains the entire path.

**Review by alexhollenbeck — APPROVED** [review]
LGTM! Consider adding a note to the documentation for this plugin saying that files starting with `.` will not be extracted.
